# Generated by Django 2.2.3 on 2019-07-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nps_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'verbose_name_plural': 'passes'},
        ),
    ]
