# Generated by Django 2.2.3 on 2019-07-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nps_django', '0002_auto_20190714_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='passholders',
        ),
        migrations.AddField(
            model_name='pass',
            name='passholder_primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps_django.Passholder'),
        ),
        migrations.AddField(
            model_name='pass',
            name='passholder_secondary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
