# Generated by Django 2.2.3 on 2019-07-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps_django', '0003_auto_20190714_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Expiration date'),
        ),
        migrations.AddField(
            model_name='pass',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
