# Generated by Django 2.2.3 on 2019-07-14 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nps_django', '0004_auto_20190714_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='passholder_primary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nps_django.Passholder'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='passholder_secondary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
