# Generated by Django 2.2.3 on 2019-07-15 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nps_django', '0005_auto_20190714_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='pass_id',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pass',
            name='passholder_primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes', to='nps_django.Passholder'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='nps_django.Park'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='passholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='nps_django.Passholder'),
        ),
    ]
