# Generated by Django 2.2.3 on 2019-07-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps_django', '0006_auto_20190715_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='online_registration_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
