# Generated by Django 2.2.3 on 2019-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps_django', '0007_pass_online_registration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='expiration_date',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='online_registration_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primary passholder name'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='pass_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Pass ID'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='phone_num',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
    ]
