# Generated by Django 2.2.3 on 2019-07-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps_django', '0008_auto_20190715_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='pass',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Expiration date'),
        ),
    ]
