# Generated by Django 2.2.3 on 2019-07-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps_django', '0010_auto_20190718_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='phone_num',
            field=models.CharField(max_length=30, verbose_name='Phone number'),
        ),
    ]
