# Generated by Django 2.2.3 on 2019-07-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps_django', '0011_auto_20190718_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration date'),
        ),
    ]
