# Generated by Django 2.2.3 on 2019-07-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps_django', '0012_auto_20190719_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
